name: Build
on: [push, workflow_dispatch]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install rpm tool
      run:
        sudo apt-get update;
        sudo apt install rpm
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build      
    - name: make
      run: npm run make
    - name: Location
      run: ls -R out/make
    - name: Store artifact for .deb
      uses: actions/upload-artifact@v3
      with:
        name: upverse_1.0.0_amd64.deb
        path: out/make/deb/x64/upverse_1.0.0_amd64.deb
#    - name: Store artifact for .rpm
#      uses: actions/upload-artifact@v3
#      with:
#        name: upverse_1.0.0-1.x86_64.rpm
#        path: out/make/rpm/x64/upverse-1.0.0-1.x86_64.rpm

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build      
    - name: make
      run: npm run make
    - name: Location
      run: ls -R out/make
    - name: Store artifact for darwin as .zip
      uses: actions/upload-artifact@v3
      with:
        name: upverse-darwin-x64-1.0.0.zip
        path: out/make/zip/darwin/x64/upverse-darwin-x64-1.0.0.zip    
      
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build      
    - name: make
      run: npm run make
    - name: Location
      run: dir out\make\squirrel.windows\x64
    - name: Store artifact for .exe
      uses: actions/upload-artifact@v3
      with:
        name: upverse-1.0.0.Setup.exe
        path: out\make\squirrel.windows\x64\upverse-1.0.0*Setup.exe
